// file: game/level/level1.ts
//
// Ember Hills — 80 × 15. Rows generated by hand but verified to all be
// exactly 80 chars; buildLevel re-validates on import.

import type { LevelSpawns } from '../types';
import { buildLevel } from './buildLevel';

const SURFACE = '###########...########...######..#########^^####...#########...#########..######';
const UNDER   = '###########...########...######..###############...#########...#########..######';
const PLAT    = '.....===.......===........===........===.........===.......===......===.........';
const AIR     = '................................................................................';
const TOP     = '################################################################################';

const ROWS = [
  TOP,    // 0  — ceiling
  AIR,    // 1
  AIR,    // 2
  AIR,    // 3
  AIR,    // 4  — ? blocks placed as entities
  PLAT,   // 5  — floating platforms
  AIR,    // 6
  AIR,    // 7  — player spawn
  SURFACE,// 8  — ground
  UNDER,  // 9
  UNDER,  // 10
  UNDER,  // 11
  UNDER,  // 12
  UNDER,  // 13
  UNDER,  // 14
];

const LEVEL = buildLevel(ROWS);

export const level1Tiles  = LEVEL.tiles;
export const LEVEL_WIDTH  = LEVEL.width;
export const LEVEL_HEIGHT = LEVEL.height;

export const level1Spawns: LevelSpawns = {
  player: { tx: 2, ty: 7 },

  enemies: [
    { type: 'walker', tx: 14, ty: 6 },
    { type: 'walker', tx: 25, ty: 6 },
    { type: 'hopper', tx: 35, ty: 6 },
    { type: 'walker', tx: 52, ty: 6 },
    { type: 'hopper', tx: 60, ty: 6 },
    { type: 'walker', tx: 70, ty: 6 },
  ],

  blocks: [
    { type: 'question', tx: 6,  ty: 4 },
    { type: 'question', tx: 27, ty: 4 },
    { type: 'question', tx: 49, ty: 4 },
  ],

  coins: [
    { tx: 6,  ty: 4 },
    { tx: 17, ty: 4 },
    { tx: 28, ty: 4 },
    { tx: 39, ty: 4 },
    { tx: 50, ty: 4 },
    { tx: 60, ty: 4 },
    { tx: 70, ty: 4 },
    { tx: 9,  ty: 7 },
    { tx: 40, ty: 7 },
    { tx: 65, ty: 7 },
  ],

  checkpoints: [
    { tx: 41, ty: 6 },
  ],

  goal: { tx: 76, ty: 2 },
};
